FROM alpine:latest
ARG TARGETARCH
RUN apk add --update --no-cache ca-certificates
ADD --chmod=400 ./THIRD_PARTY_LICENSES.txt /THIRD_PARTY_LICENSES.txt
ADD --chmod=500 ./configs/default.json /models/default.json
ADD --chmod=500 ./configs/azure.json /models/azure.json
ADD --chmod=500 ./configs/aws.json /models/aws.json
ADD --chmod=500 ./configs/gcp.json /models/gcp.json
ADD --chmod=500 ./configs/alibaba.json /models/alibaba.json
ADD --chmod=500 ./configs/oracle.json /models/oracle.json
ADD --chmod=500 ./configs/otc.json /models/otc.json
RUN chown -R 1001:1001 /models
COPY ./bin/opencost-${TARGETARCH} /go/bin/app
USER 1001
ENTRYPOINT ["/go/bin/app"]
